# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKiYAfvbWVzYaMJ80Wu4XSaDfVlkKwQd
"""

from flask import Flask, request, jsonify
from roboflow import Roboflow
from pyngrok import ngrok
from threading import Thread

# 🔹 تحميل الموديل من Roboflow
print("Loading Roboflow model...")
rf = Roboflow(api_key="tN8RCHc8406wlBLQoCBx")
project = rf.workspace("yomnasoror").project("medical-waste")
model = project.version(1).model
print("✅ Model loaded successfully!")

# 🔹 إنشاء تطبيق Flask
app = Flask(__name__)

@app.route("/", methods=["GET"])
def home():
    return "✅ Medical Waste Classification API is running!"

@app.route("/predict", methods=["POST"])
def predict():
    if "image" not in request.files:
        return jsonify({"error": "No image uploaded"}), 400
    image = request.files["image"]
    result = model.predict(image).json()
    return jsonify(result)

# 🔹 استخدمي منفذ جديد
port = 5001  # غيري عن 5000
public_url = ngrok.connect(port).public_url
print(f"🚀 Public API URL: {public_url}")

# Run the Flask app in a separate thread
def run_flask_app():
    app.run(port=port, debug=True, use_reloader=False)

flask_thread = Thread(target=run_flask_app)
flask_thread.start()

from flask import Flask, request, jsonify
from roboflow import Roboflow
import io
from PIL import Image

app = Flask(__name__)

# تحميل الموديل من Roboflow
rf = Roboflow(api_key="tN8RCHc8406wlBLQoCBx")
project = rf.workspace("yomnasoror").project("medical-waste")
model = project.version(1).model

@app.route("/predict", methods=["POST"])
def predict():
    if "image" not in request.files:
        return jsonify({"error": "No image uploaded"}), 400

    image_file = request.files["image"]
    image = Image.open(image_file)

    # تحويل الصورة إلى bytes
    img_bytes = io.BytesIO()
    image.save(img_bytes, format="PNG")
    img_bytes.seek(0)

    # التنبؤ
    result = model.predict(img_bytes).json()

    if len(result["predictions"]) == 0:
        return jsonify({"prediction": None, "message": "No object detected"})

    pred = result["predictions"][0]

    return jsonify({
        "class": pred["class"],
        "confidence": float(pred["confidence"])
    })

# تشغيل API
if __name__ == "__main__":
 app.run(host="0.0.0.0", port=5001)